django_site_main/app/urls.py
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from app import views

urlpatterns = patterns('',

                       url(r'^$', views.home, name='home'),
                       url(r'^', include('django.contrib.auth.urls')),
                       url(r'^register', views.register, name='register'),
                       url(r'^edit_marks/', views.edit_marks, name='edit_marks'),
                       url(r'^commit_edit/(\d+)', views.mark_edit, name='commit_edit'),
                       url(r'^grades/$', views.grades, name='grades'),
                       url(r'^gradesDynamic/$', views.gradesDynamic, name='gradesDynamic'),
                       url(r'^gradesDynamic/filter$', views.gradesFilter, name='gradesFilter'),
                       url(r'^oauth_callback/$', views.oauth_callback, name='oauth'),
                       url(r'^oauth_init/$', views.oauth_init, name='oauth'),

)

django_site_main/django_site_main/urls.py
"""
Definition of urls for django_site_main.
"""

from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from django.contrib import admin
import os
admin.autodiscover()

import settings
urlpatterns = patterns('',
                       url(r'^', include('app.urls', namespace='app')),

                       # url(r'^login/$',
                       # 'django.contrib.auth.views.login',
                       # {
                       #         'template_name': 'app/login.html',
                       #         'authentication_form': BootstrapAuthenticationForm,
                       #         'extra_context':
                       #         {
                       #             'title':'Log in',
                       #             'year':datetime.now().year,
                       #         }
                       #     },
                       #     name='login'),
                       # url(r'^logout$',
                       #     'django.contrib.auth.views.logout',
                       #     {
                       #         'next_page': '/',
                       #     },
                       #     name='logout'),

                       # url(r'^$', 'app.views.home', name='home'),
                       # url(r'^contact$', 'app.views.contact', name='contact'),
                       # url(r'^about', 'app.views.about', name='about'),
                       # url(r'^oauth_callback', 'app.views.oauth_callback', name='oauth'),
                       # url(r'^oauth_init', 'app.views.oauth_init', name='oauth'),
                       # url(r'^login/$',
                       #     'django.contrib.auth.views.login',
                       #     {
                       #         'template_name': 'app/login.html',
                       #         'authentication_form': BootstrapAuthenticationForm,
                       #         'extra_context':
                       #         {
                       #             'title':'Log in',
                       #             'year':datetime.now().year,
                       #         }
                       #     },
                       #     name='login'),
                       # url(r'^logout$',
                       #     'django.contrib.auth.views.logout',
                       #     {
                       #         'next_page': '/',
                       #     },
                       #     name='logout'),
                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_site_main/app/templates/app/edit_marks.html
{% extends "app/layout.html" %}

{% block content %}
<div class="clearfix">
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <div class="list-group">

        <script type="text/javascript">
          updateHandler = function (id) {
            var frm = $('#f_i_' + id);
            frm.ajaxForm(function (data) {
              out = $('#i_' + id);
              out.html(data);
              updateHandler(id);
            })
          }

        </script>

        {% for el in field_list %}
        <div class="row list-group-item">
            <div class="col-md-8">
                {% include "app/edit_mark.html" with form=el.form i_id=el.i_id mode=el.mode name=el.name %}
                <script>updateHandler({{ el.i_id }});</script>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

django_site_main/app/templates/app/gradesDynamic.html
{% extends "app/layout.html" %}
{% load static %}
{%block gradesDynamic%}active{%endblock%}
{% block content %}
<div class="clearfix">
    <style type="text/css">
        #add-form {
            width:35px; height:35px;
            background:url({% static 'app/media/img-add.png' %});
            margin-top: 15pxl; margin-bottom: 15px;
            cursor: pointer;
        }

        #grades-form p {
            position: relative;
            width: 400px;
            margin-top: 20px;
        }

        .course-display {
            width: 300px !important;
        }


        .course-display, .mark-select {
            position: absolute;
            right: 0px;
        }
        .mark-select {
            display: none;
        }


        .ui-state-focus {
            background: none !important;
            font-weight: normal !important;
            color: grey !important;
        }
        .ui-state-focus a,
        .ui-state-focus a:hover,
        .ui-state-focus a:link,
        .ui-state-focus a:visited {
        color: #c77405;
            text-decoration: none;
        }
        .ui-state-focus .ui-icon {
            background-image: url("images/ui-icons_ef8c08_256x240.png");
        }


        #tile-template {
            position: absolute;
            right: 0px;
        }
        .ui-menu-item {
            font-size: 14px !important;
        }
        .ui-menu-icons .ui-menu-item {
            padding-left: 2em;
        }

        ul.errorlist li {
            color: red !important;
        }


        .tile {
            background: white;
            margin-left: 5px;
            margin-right: 5px;
            width: 27px;
            height: 27px;
            display: inline-block !important;
            border:2px solid #248F24;
            cursor: pointer;
            text-align: center;
            padding: 0px;
            padding-top: 3px;
            font-size: 85%;
        }
        .tile:hover {
            background: #AAE2AA;
            <!--border:2px solid black;-->
        }

        #alg-form {
            border: 1px solid black;
            position: absolute;
            padding: 10px;
        }
        #grades-form {
            margin-left: 450px;
        }


    </style>

    <script type="text/javascript">
    var form_count = 1

    $(document).ready(function(){

        $("#grades-form").submit(function(e){
            checked_sub=[]
            checked_sem=[]
            $("#id_form-0-algorithmSub").find("input:checked").each(function(){checked_sub.push(parseInt($(this).val()))})
            $("#id_form-0-algorithmSem").find("input:checked").each(function(){checked_sem.push(parseInt($(this).val()))})


            cur_action = $(this).attr("action")
            selected_subject = $("#id_markSubject").val()
            selected_seminar = $("#id_semSub").val()
            is_selected_seminar = $("#id_semSubChecked").is(":checked")
            is_selected_subject = $("#id_markSubjectChecked").is(":checked")

            new_action = cur_action + "?algorithmSub=" + checked_sub + "&algorithmSem=" + checked_sem + "&selectedSub=" +
            selected_subject + "&selectedSem=" + selected_seminar + "&semSubChecked=" + is_selected_seminar + "&markSubChecked=" + is_selected_subject
            $(this).attr("action", new_action)
        })


        function registerFunctions() {
            $(".course-display").autocomplete({
                source: "{% url 'app:gradesFilter' %}",
                minLength: 2,
                select:function(event, ui) {
                    course_id = "#" + this.id.replace("_display", "")
                    $(course_id).val(ui.item.id)
                }
            });

            $(".tile").click(function() {
                $(this.parentNode.childNodes).css("background", "")
                $(this).css("background", "#AAE2AA")

                selected_mark = parseInt(this.className.match(/\d+/)[0])
                mark_form = $(this.parentNode.parentNode).find(".mark-select")[0]
                $(mark_form).val(selected_mark)
            });

            courses_to_hide = $(".course-input")
            for (i = 0; i < courses_to_hide.length; i++) {
                $(courses_to_hide[i].parentNode).css("display", "none")
                $($(courses_to_hide[i].parentElement).prev("ul.errorlist")).css("display", "none")
            }
        }

        clean_tile_copy = $($("#tile-template")[0]).clone()[0]
        $(clean_tile_copy).css("display", "inline-block")

        mark_select = $(".mark-select")
        if (mark_select.length > 1) {
            for (i = 0; i < mark_select.length; i++) {
                $(mark_select[i].parentElement)[0].appendChild($(clean_tile_copy).clone()[0])
                $("<hr>").insertAfter($(mark_select[i].parentElement))
                $("<hr>").insertAfter($(mark_select[i].parentElement))

                if ($(mark_select[i]).val() != "") {
                    value = $(mark_select[i]).val()
                    if (value != null)
                        $($($(mark_select[i].parentElement)[0]).find(".tile-"+value)).css("background", "#AAE2AA")
                }
            }
        } else {
            $(mark_select[0].parentElement)[0].appendChild($(clean_tile_copy).clone()[0])
            $("<hr>").insertBefore("#add-form")
            $("<hr>").insertBefore("#add-form")
        }

        registerFunctions()

        clean_sel_copy = $($(".mark-select")[0].parentElement).clone()[0]
        clean_inp_copy = $($(".course-input")[0].parentElement).clone()[0]
        clean_dsp_copy = $($(".course-display")[0].parentElement).clone()[0]


        $("#add-form").click(function(){
            form_count++
            $("#id_form-TOTAL_FORMS").val(form_count)

            inputs_list = $(".course-input")
            last_input = inputs_list[inputs_list.length - 1]
            last_index = parseInt(last_input.id.match(/\d+/)[0])
            new_index = last_index + 1

            new_input = $($(clean_inp_copy).clone()[0])
            id = new_input.find("input")[0].id.replace(/\d+/, new_index)
            name = new_input.find("input")[0].name.replace(/\d+/, new_index)
            new_input.find("input")[0].id = id
            new_input.find("input")[0].name = name
            new_input.insertBefore("#add-form")

            new_display = $($(clean_dsp_copy).clone()[0])
            id = new_display.find("input")[0].id.replace(/\d+/, new_index)
            name = new_display.find("input")[0].name.replace(/\d+/, new_index)
            new_display.find("input")[0].id = id
            new_display.find("input")[0].name = name
            new_display.insertBefore("#add-form")

            new_select = $($(clean_sel_copy).clone()[0])
            id = new_select.find("select")[0].id.replace(/\d+/, new_index)
            name = new_select.find("select")[0].name.replace(/\d+/, new_index)
            new_select.find("select")[0].id = id
            new_select.find("select")[0].name=name
            new_select.insertBefore("#add-form")

            $("<hr>").insertBefore("#add-form")
            $("<hr>").insertBefore("#add-form")

            registerFunctions()
        });
    });


    </script>



    <div id="tile-template" style="display: none;">
        <div class="tile tile-0">B</div>
        <div class="tile tile-4">2</div>
        <div class="tile tile-6">3</div>
        <div class="tile tile-7">3+</div>
        <div class="tile tile-8">4</div>
        <div class="tile tile-9">4+</div>
        <div class="tile tile-10">5</div>
        <div class="tile tile-11">5!</div>
    </div>

    <form id="alg-form">

        <p>
            <label for="id_form-0-algorithmSub_0">Wybierz algorytm rekomendacji przedmiotow:</label> <ul id="id_form-0-algorithmSub">
            <li><label for="id_form-0-algorithmSub_0"><input id="id_form-0-algorithmSub_0" name="form-0-algorithmSub" type="checkbox" value="1" /> strategia wykorzystujaca algorytm regulowy</label></li>
            <li><label for="id_form-0-algorithmSub_1"><input id="id_form-0-algorithmSub_1" name="form-0-algorithmSub" type="checkbox" value="2" /> lista priorytetowa najlatwiejszych przedmiotow</label></li>
            <li><label for="id_form-0-algorithmSub_2"><input id="id_form-0-algorithmSub_2" name="form-0-algorithmSub" type="checkbox" value="3" /> dobierz w sposob losowy</label></li>
            <li><label for="id_form-0-algorithmSub_3"><input id="id_form-0-algorithmSub_3" name="form-0-algorithmSub" type="checkbox" value="4" /> strategia najblizszych sasiadow</label></li>
            </ul></p>
        <p>
            <label for="id_semSub"><input id="id_semSubChecked" name="semSubChecked" type="checkbox" value="1" />Wybierz seminarium do rekomendacji przedmiotow</label></br>
            <select id="id_semSub" name="semSub">
                <option value="51">Systemy rozproszone</option>
                <option value="52">Języki programowania</option>
                <option value="53">Zagadnienia programowania obiektowego</option>
                <option value="54">Wybrane aspekty inżynierii oprogramowania</option>
                <option value="55">Analiza, wizualizacja i optymalizacja oprogramowania</option>
                <option value="56">Innowacyjne zastosowania informatyki</option>
                <option value="57">Molekularna biologia obliczeniowa</option>
                <option value="58">Algorytmika</option>
                <option value="59">Metody numeryczne</option>
                <option value="60">Matematyka w informatyce</option>
            </select>
        </p>
            <p><label for="id_form-0-algorithmSem_0">Wybierz algorytm rekomendacji seminarium:</label> <ul id="id_form-0-algorithmSem">
            <li><label for="id_form-0-algorithmSem_0"><input id="id_form-0-algorithmSem_0" name="form-0-algorithmSem" type="checkbox" value="1" /> strategia wykorzystujaca algorytm lasow losowych</label></li>
            <li><label for="id_form-0-algorithmSem_1"><input id="id_form-0-algorithmSem_1" name="form-0-algorithmSem" type="checkbox" value="2" /> strategia najblizszych sasiadow</label></li>
            </ul>
        </p>
        <p>
            <label for="id_markSubject"><input id="id_markSubjectChecked" name="markSubjectChecked" type="checkbox" value="1" />Wybierz przedmiot do predykcji oceny:</label></br>
            <select id="id_markSubject" name="markSubject">
                <option value="31">Zaawansowane systemy operacyjne</option>
                <option value="32">Programowanie mikrokontrolerow</option>
                <option value="33">Kompresja danych</option>
                <option value="34">Przetwarzanie duzych danych</option>
                <option value="35">Programowanie w logice</option>
                <option value="36">Wstęp do biologii obliczeniowej</option>
                <option value="37">Zaawansowane bazy danych</option>
                <option value="38">Systemy uczące się</option>
                <option value="39">Sztuczna inteligencja i systemy doradcze</option>
                <option value="40">Data mining</option>
                <option value="41">Algorytmika</option>
                <option value="42">Algorytmy tekstowe</option>
                <option value="43">Weryfikacja wspomagana komputerowo</option>
                <option value="44">Wnioskowanie w serwisach i systemach informatycznych</option>
                <option value="45">Teoria informacji</option>
                <option value="46">Kryptografia</option>
                <option value="47">Matematyka obliczeniowa 2</option>
                <option value="48">Statystyka 2</option>
                <option value="49">Rachunek prawdopodobienstwa 2</option>
                <option value="50">Optymalizacja 1</option>
            </select>
        </p>

    </form>

    <form id="grades-form" action="{% url 'app:gradesDynamic' %}" method="POST">
        {% csrf_token %}

        {{ formset.as_p }}

        <div id="add-form"></div>
        <input type="submit" value="Wyślij"/>
    </form>
</div>

{% endblock %}

django_site_main/app/templates/app/gradesResult.html
{% extends "app/layout.html" %}

{% block content %}
 
<div class="clearfix">
{% if alg.0 %}
<h2> Algorytm regułowy </h2>
<h3> Lista proponowanych przedmiotów: </h3>
<ol>
    {% for name,url,avg,chance,proc,id_n,id_u in recomSub1 %}
    <li>
    <h4> {{ name }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ id_n }}','{{id_u}}')" id="{{id_u}}">info</a> </font> </h4>
    <div id="{{ id_n }}" style="display:none">
                <h5>
                    <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ url }}">
                        Strona przedmiotu </a></h5>
                <h5>Średnia z ocen: {{avg}} </h5>  
                <h5>Procentowa zdawalność: {{chance}} % </h5>
                <h5>Procent zapisanych studentów: {{proc}} % </h5> 
    </div>
    </li>
    {% endfor %}
</ol>
{% endif %}
{% if alg.1 %}
<h2> Najłatwiejsze przedmioty </h2>
<h3> Lista proponowanych przedmiotów: </h3>
<ol>
    {% for name,url,avg,chance,proc,id_n,id_u in recomSub2 %}
    <li>
    <h4> {{ name }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ id_n }}','{{id_u}}')" id="{{id_u}}">info</a> </font> </h4>
    <div id="{{ id_n }}" style="display:none">
                <h5>
                    <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ url }}">
                        Strona przedmiotu </a></h5>
                <h5>Średnia z ocen: {{avg}} </h5>  
                <h5>Procentowa zdawalność: {{chance}} % </h5>
                <h5>Procent zapisanych studentów: {{proc}} % </h5> 
    </div>
    </li>
    {% endfor %}
</ol>
{% endif %}
{% if alg.2 %}
<h2> Szczęśliwy traf </h2>
<h3> Lista proponowanych przedmiotów: </h3>
<ol>
    {% for name,url,avg,chance,proc,id_n,id_u in recomSub3 %}
    <li>
    <h4> {{ name }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ id_n }}','{{id_u}}')" id="{{id_u}}">info</a> </font> </h4>
    <div id="{{ id_n }}" style="display:none">
                <h5>
                    <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ url }}">
                        Strona przedmiotu </a></h5>
                <h5>Średnia z ocen: {{avg}} </h5>  
                <h5>Procentowa zdawalność: {{chance}} % </h5>
                <h5>Procent zapisanych studentów: {{proc}} % </h5> 
    </div>
    </li>
    {% endfor %}
</ol>
{% endif %}

{% if alg.3 %}
<h2> Strategia najbliższych sasiadów </h2>
<h3> Lista proponowanych przedmiotów: </h3>
<ol>
    {% for name,url,avg,chance,proc,id_n,id_u in recomSub4 %}
    <li>
    <h4> {{ name }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ id_n }}','{{id_u}}')" id="{{id_u}}">info</a> </font> </h4>
    <div id="{{ id_n }}" style="display:none">
                <h5>
                    <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ url }}">
                        Strona przedmiotu </a></h5>
                <h5>Średnia z ocen: {{avg}} </h5>  
                <h5>Procentowa zdawalność: {{chance}} % </h5>
                <h5>Procent zapisanych studentów: {{proc}} % </h5> 
    </div>
    </li>
    {% endfor %}
</ol>
{% endif %}

{% if isSelectedSem %}
<h2> Przedmioty rekomendowane dla seminarium {{ semSub }} </h2>
<h3> Lista proponowanych przedmiotów: </h3>
<ol>
    {% for name,url,avg,chance,proc,id_n,id_u in recomSub5 %}
    <li>
    <h4> {{ name }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ id_n }}','{{id_u}}')" id="{{id_u}}">info</a> </font> </h4>
    <div id="{{ id_n }}" style="display:none">
                <h5>
                    <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ url }}">
                        Strona przedmiotu </a></h5>
                <h5>Średnia z ocen: {{avg}} </h5>
                <h5>Procentowa zdawalność: {{chance}} % </h5>
                <h5>Procent zapisanych studentów: {{proc}} % </h5>
    </div>
    </li>
    {% endfor %}
</ol>
{% endif %}

{% if sem %}
<h2> Proponowane seminaria</h2>

{% if recomSem.0 %}
<h3>Seminarium rekomendowane wg algorytmu lasów losowych </h3>
<ul>

    <h4> {{ recomSem.0.0 }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ recomSem.0.5 }}','{{ recomSem.0.6 }}')" id="{{recomSem.0.6}}">info</a> </font> </h4>
    <div id="{{ recomSem.0.5 }}" style="display:none">
        <h5>
            <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ recomSem.0.1  }}">
                Strona przedmiotu </a></h5>
        <h5>Średnia z ocen: {{recomSem.0.2}} </h5>  
        <h5>Procentowa zdawalność: {{recomSem.0.3}} % </h5>
        <h5>Procent zapisanych studentów: {{recomSem.0.4}} % </h5> 
    </div>
</ul>
{% endif %}

{% if recomSem.1 %}
<h3>Seminarium rekomendowane wg strategii najbliższych sąsiadów </h3>
<ul>
    <h4> {{ recomSem.1.0 }} <font size="3"> &nbsp;&nbsp; <a href="javascript:pokazUkryj('{{ recomSem.1.5 }}','{{ recomSem.1.6 }}')" id="{{recomSem.1.6}}">info</a> </font> </h4>
    <div id="{{ recomSem.1.5 }}" style="display:none">
        <h5>
            <a href="https://usosweb.mimuw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod={{ recomSem.1.1  }}">
                Strona przedmiotu </a></h5>
        <h5>Średnia z ocen: {{recomSem.1.2}} </h5>  
        <h5>Procentowa zdawalność: {{recomSem.1.3}} % </h5>
        <h5>Procent zapisanych studentów: {{recomSem.1.4}} % </h5> 
    </div>
</ul>
{% endif %}

{% endif %}

{% if isSelectedSub %}
    <h3>Proponowana ocena z {{ predMarkSub }}</h3>
    <h4>{{ predMark }}</h4>
{% endif %}




<!-- zrodlo : http://www.forumweb.pl/html/rozwin-zwin-temat,21393 -->
<script type="text/javascript">
<!--
function pokazUkryj(id,id2)
{
document.getElementById(id).style.display = (document.getElementById(id).style.display == "none") ? "block" : "none";
document.getElementById(id2).innerHTML = (document.getElementById(id2).innerHTML === "info") ? "zwin" : "info";
}
-->
</script>
</div>


{% endblock %}

django_site_main/app/templates/app/index.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{%block home%}active{%endblock%}
{% block content %}

		<div id="adbox" style="padding-top: 0px;">
			<div class="clearfix">
				<img src="{% static 'app/media/hermes-foot.png' %}" alt="Img" height="229" width="356" style="margin: 40px;">
				<div class="detail" style="width: 500px;">
					<h1>ZPP Hermes<br>
                        System wspomagający studentów</h1>
					<p>
						w wyborze ścieżki studiów
					</p>
				</div>
			</div>
		</div>

<!--<div class="jumbotron">-->
    <!--<h1>Hermes</h1>-->

    <!--<h2>{{ test }}</h2>-->

    <!--<p class="lead">Zapraszamy do skorzystania z systemu wspomagającego wybór przedmiotów w czasie rekrutacji.</p>-->

    <!--<p><a href="{% url 'app:grades' %}" class="btn btn-primary btn-large">Wprowadź oceny &raquo;</a></p>-->

    <!--<p><a href="{% url 'app:gradesDynamic' %}" class="btn btn-primary btn-large">Oceny test &raquo;</a></p>-->
<!--</div>-->


{% endblock %}

django_site_main/app/templates/app/layout.html
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<title>ZPP Hermes</title>
	<link rel="stylesheet" href="{% static 'app/content/style.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'app/scripts/jquery-ui-1.11.4/jquery-ui.min.css' %}"/>
    <script src="{% static 'app/scripts/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-ui-1.11.4/jquery-ui.min.js' %}"></script>
</head>
<body>
	<div id="header">
		<div class="clearfix">
			<div class="logo">
				<a href="{% url 'app:home' %}"><img src="{% static 'app/media/logo-hermes.png' %}" alt="LOGO" height="120" width="289"></a>
			</div>
			<ul class="navigation">
				<li class="{%block home%}{%endblock%}">
					<a href="{% url 'app:home' %}">Home</a>
				</li>
                <li class="{%block gradesDynamic%}{%endblock%}">
					<a href="{% url 'app:gradesDynamic' %}">Wprowadź oceny</a>
				</li>
                <li class="">
					<a href="{% url 'app:edit_marks' %}">Edytuj oceny</a>
				</li>

				{% if user.is_authenticated %}
				<li><span style="margin-left: 20px;">Zalogowano: {{ user.username }}</span></li>
        		<li><a href="javascript:document.getElementById('logoutForm').submit()" style="color: #CC0000;">Log off</a></li>

				<form id="logoutForm" action="{% url 'app:logout' %}" method="post" class="navbar-right">
					{% csrf_token %}
				</form>
				{% else %}
				<li><a href="{% url 'app:register' %}">Register</a></li>
				<li><a href="{% url 'app:login' %}">Log in</a></li>
				{% endif %}

			</ul>
		</div>
	</div>
	<div id="contents">
        {% block content %}{% endblock %}

	</div>
	<div id="footer">
		<div class="clearfix">
			<div class="section">
				<h4>Nowości</h4>
				<p>
					Hermes rusza!
				</p>
			</div>
			<div class="section contact">
				<h4>Kontakt</h4>
				<p>
					<span>Email:</span> info-hermes@google.com
				</p>
                <p>
					<span>Telefon:</span> 000-000-000
				</p>
			</div>
			<div class="section">
				<h4>Nic ciekawego</h4>
			</div>
		</div>
		<div id="footnote">
			<div class="clearfix">
				<p>
					{{ year }} - ZPP
				</p>
			</div>
		</div>
	</div>
</body>
</html>

django_site_main/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}